
version: '3'

services:
  monitoramento-aplicacoes:
    image: worker
    build:
      context: ./src/Muniz.Desafio.Worker
    networks:
      - desafio-network
    depends_on:
      - "desafio-bd"

  desafio-bd:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - desafio-network

networks: 
    desafio-network:
      driver: bridge
